name: Actions Test
on: [push]
env:
  GLOBAL_VAR: "This is globally available!"
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'Hello World'
    - run: pwd
    - run: ls -la
    
  clone_job:
    runs-on: ubuntu-latest
    steps:
    - run: ls -la
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - run: echo '${{ github.repository }}'
    - run: ls -la
    - run: cat file1.txt
    - run: echo "this is new text" >> file1.txt
    
  mkdir_job:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: mkdir new_folder
    - run: ls -la
    
  mvfile_job:
    runs-on: ubuntu-latest
    steps:
    - run: ls -la
    - run: mkdir new_folder2
    - run: cd new_folder2
    - run: touch secretfile.txt
    - run: ls -la

  env_job:
    runs-on: ubuntu-latest
    env:
      LOCAL_VAR: "This is locally available"
    steps:
    - name: Running global variable
      run: echo $GLOBAL_VAR
    - name: Running local variable
      run: echo $LOCAL_VAR
    - name: Running secret variable
      run: echo "${{secrets.SECRET_TEXT}}"
